### ISSUE TITLE
输入两个无环的单向链表，找出它们的第输入两个无环的单向链表，找出它们的第一个公共结点，如果没有公共节点则返回空。(这里注意因为传入数据是链表，所以错误测试数据的提示是用其他方式显示的，保证传入数据是正确的)一个公共结点，如果没有公共节点则返回空。(这里注意因为传入数据是链表，所以错误测试数据的提示是用其他方式显示的，保证传入数据是正确的)

### ISSUE THREAD

**Issue by 1490386786** [1490386786/verify#3]
输入两个无环的单向链表，找出它们的第一个公共结点，如果没有公共节点则返回空。(这里注意因为传入数据是链表，所以错误测试数据的提示是用其他方式显示的，保证传入数据是正确的)
输入两个无环的单向链表，找出它们的第一个公共结点，如果没有公共节点则返回空。(这里注意因为传入数据是链表，所以错误测试数据的提示是用其他方式显示的，保证传入数据是正确的)

**Comment by weizuxiao911** [comment]
大大发发发 多大的
